name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
            contents: "read"
            id-token: "write"
            pull-requests: "write"
        steps:
            - uses: actions/checkout@v2.2.6
            - uses: ArtiomTr/jest-coverage-report-action@Do-not-fail-if-no-checks-read-permission